version: 2
jobs:
  build:
    working_directory: ~/qlik-tusdotnet

    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - checkout

      - run:
          name: Build
          command: |
            dotnet restore Source/tusdotnet.sln
            dotnet build Source/tusdotnet.sln -c Release

      - run:
          name: Run Tests
          command: |
            dotnet test -c Release --no-build Source/tusdotnet.test

      - run:
          name: Set build version
          command: |
            set -x
            if [ -n "${CIRCLE_TAG}" ]; then
              version=${CIRCLE_TAG#v}
            else
              version=$(git describe --tags --match 'v[0-9]*' --abbrev=0)-$CIRCLE_BUILD_NUM
              version=${version#v}
            fi
            echo "$version" > ./version.txt
            echo "Version from version.txt:"
            cat ./version.txt

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/

experimental:
  notify:
    branches:
      only:
        - master
