version: 2
jobs:
  build:
    working_directory: ~/qlik-tusdotnet

    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - checkout

      - run:
          name: Build
          command: |
            dotnet restore Source/tusdotnet.sln
            dotnet build Source/tusdotnet.sln -c Release

      - run:
          name: Run Tests
          command: |
            dotnet test -c Release --no-build Source/tusdotnet.test

      - run:
          name: Set build version
          command: |
            set -x
            if [ -n "${CIRCLE_TAG}" ]; then
              version=${CIRCLE_TAG#v}
            else
              version=$(git describe --tags --match 'v[0-9]*' --abbrev=0)-$CIRCLE_BUILD_NUM
              version=${version#v}
            fi
            echo "$version" > ./version.txt
            echo "Version from version.txt:"
            cat ./version.txt

      - run:
          name: Pack and publish
          command: |
            version=$(cat ./version.txt)
            echo "Circle branch is: ${CIRCLE_BRANCH}"
            echo "Circle tag is: ${CIRCLE_TAG}"

            if [ "${CIRCLE_BRANCH}" == "master" ] || [ -n "${CIRCLE_TAG}" ]; then
              echo "Branch is master or tag: Pushing nuget package version: $version to artifactory."
              dotnet pack -c Release -p:PackageVersion=$version -o ./nupkgs ./Source/tusdotnet/tusdotnet.csproj
              dotnet nuget push ./nupkgs/qlik-tusdotnet*.nupkg -k ${NUGET_USER}:${NUGET_PASS} -s https://qliktech.jfrog.io/qliktech/api/nuget/qlik-nugets-local
            # else
            #   echo "Branch is not master or tag: Pushing nuget package version: ${CIRCLE_BRANCH}-$version to artifactory."
            #   dotnet pack -c Release -p:PackageVersion=${CIRCLE_BRANCH}-$version -o ./nupkgs ./Source/tusdotnet/tusdotnet.csproj
            #   find ./nupkgs -name '*.nupkg' | xargs -i dotnet nuget push {} -k ${NUGET_CRED} -s https://qliktech.jfrog.io/qliktech/api/nuget/qlik-nugets-local
            fi
            
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/

experimental:
  notify:
    branches:
      only:
        - master
